export const VEHICLES_REQUESTED = 'VEHICLES_REQUESTED';
export const VEHICLES_SUCCEEDED = 'VEHICLES_SUCCEEDED';
export const VEHICLES_FAILED = 'VEHICLES_FAILED';


export const VEHICLE_STATUS_UPDATE_REQUESTED = 'VEHICLE_STATUS_UPDATE_REQUESTED';
export const VEHICLE_STATUS_UPDATE_SUCCEEDED = 'VEHICLE_STATUS_UPDATE__SUCCEEDED';
export const VEHICLE_STATUS_UPDATE_FAILED = 'VEHICLE_STATUS_UPDATE_FAILED';

